POST http://localhost:3001/api/todos 
Content-Type: application/json 

[
  {
    "text": "My new todo",
    "description": "this is the description"
  },
  {
    "text": "My new todo",
    "description": "this is the description"
  }
]